import "./js/sections/index/hero";
import "./js/sections/index/filters.js";
import "./js/sections/index/products.js"
import "./js/sections/index/popular.js"
import "./js/sections/index/discount.js"
import "./js/sections/index/pagination.js"
import "./js/sections/index/product.js"
import "./js/sections/components/footer-modal.js";
import "./js/sections/index/products-modal.js";
import "./js/sections/index/products-add.js";